const { execute } = require("./L4v10");

module.exports = {
  name: "uinfo",
  aliases: ["whois", "user"],
  usage: "userinfo-",
  description: "Get advance stats of yourself",
  execute(message, args, Discord){


    
      const embed = new Discord.MessageEmbed()
      var user = message.mentions.users.first();
          embed.setTitle('User Information')
          embed.addField('Username', user.username)
          embed.addField('User ID', user.id)
          embed.addField('User Tag', user.tag)
          embed.addField('User Roles', member.roles)
          embed.setColor(0x00FF93)
          embed.setThumbnail(user.displayAvatarURL())
          embed.setFooter('Generated by Tubabot!')
       message.channel.send(embed);
        



      
      }



    }



